CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `username` VARCHAR(32) NOT NULL COMMENT 'username',
    `password` VARCHAR(128) NOT NULL COMMENT 'encrypted password',
    `student_id` VARCHAR(50) DEFAULT NULL COMMENT 'legacy student id',
    `real_name` VARCHAR(100) DEFAULT NULL COMMENT 'real name',
    `nickname` VARCHAR(64) DEFAULT NULL COMMENT 'nickname',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT 'avatar url',
    `phone` VARCHAR(20) DEFAULT NULL COMMENT 'phone',
    `email` VARCHAR(100) DEFAULT NULL COMMENT 'email',
    `dormitory` VARCHAR(100) DEFAULT NULL COMMENT 'dormitory',
    `grade` VARCHAR(20) DEFAULT NULL COMMENT 'grade',
    `professional_id` BIGINT DEFAULT NULL COMMENT 'professional id',
    `bio` VARCHAR(500) DEFAULT NULL COMMENT 'profile bio',
    `role` VARCHAR(20) NOT NULL DEFAULT 'STUDENT' COMMENT 'STUDENT/ADMIN',
    `publish_permission` TINYINT NOT NULL DEFAULT 1 COMMENT '0 no permission, 1 allowed',
    `permission_review_status` TINYINT NOT NULL DEFAULT 1 COMMENT '0 pending, 1 approved, 2 rejected',
    `wallet_balance` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'wallet balance',
    `frozen_amount` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'frozen amount',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '0 disabled, 1 active',
    `account_status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 normal, 2 disabled',
    `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'created time',
    `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
        COMMENT 'updated time',
    `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'logical delete flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_username` (`username`),
    UNIQUE KEY `uk_user_student_id` (`student_id`),
    KEY `idx_user_phone` (`phone`),
    KEY `idx_user_email` (`email`),
    KEY `idx_user_role` (`role`),
    KEY `idx_user_publish_permission` (`publish_permission`),
    KEY `idx_user_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='user';
