CREATE TABLE IF NOT EXISTS `service_order` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `order_number` VARCHAR(100) NOT NULL COMMENT 'order number',
    `service_id` BIGINT UNSIGNED NOT NULL COMMENT 'service id',
    `buyer_id` BIGINT UNSIGNED NOT NULL COMMENT 'buyer user id',
    `seller_id` BIGINT UNSIGNED NOT NULL COMMENT 'seller user id',
    `quantity` INT NOT NULL DEFAULT 1 COMMENT 'quantity',
    `unit_price` DECIMAL(10, 2) NOT NULL COMMENT 'unit price',
    `total_amount` DECIMAL(10, 2) NOT NULL COMMENT 'total amount',
    `trade_type` TINYINT NOT NULL COMMENT '1 offline, 2 online',
    `trade_location_id` BIGINT UNSIGNED DEFAULT NULL COMMENT 'trade location id',
    `payment_status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 unpaid, 2 paid, 3 refunded',
    `order_status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 unpaid, 2 pending ship, 3 pending receipt, 4 completed, 5 cancelled, 6 failed',
    `frozen_amount` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'frozen amount',
    `payment_method` TINYINT NOT NULL DEFAULT 1 COMMENT '1 wallet',
    `payment_time` DATETIME DEFAULT NULL COMMENT 'payment time',
    `seller_ship_time` DATETIME DEFAULT NULL COMMENT 'seller ship time',
    `buyer_confirm_time` DATETIME DEFAULT NULL COMMENT 'buyer confirm time',
    `refund_status` TINYINT NOT NULL DEFAULT 0 COMMENT '0 none, 1 pending, 2 approved, 3 rejected, 4 completed',
    `refund_reason` VARCHAR(500) DEFAULT NULL COMMENT 'refund reason',
    `refund_request_time` DATETIME DEFAULT NULL COMMENT 'refund request time',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT 'remark',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logical delete flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_service_order_number` (`order_number`),
    KEY `idx_service_order_buyer` (`buyer_id`, `create_time`),
    KEY `idx_service_order_seller` (`seller_id`, `create_time`),
    KEY `idx_service_order_service` (`service_id`),
    KEY `idx_service_order_status` (`order_status`, `payment_status`),
    KEY `idx_service_order_refund` (`refund_status`, `refund_request_time`),
    CONSTRAINT `fk_service_order_service` FOREIGN KEY (`service_id`) REFERENCES `service` (`id`),
    CONSTRAINT `fk_service_order_buyer` FOREIGN KEY (`buyer_id`) REFERENCES `user` (`id`),
    CONSTRAINT `fk_service_order_seller` FOREIGN KEY (`seller_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='service order';

CREATE TABLE IF NOT EXISTS `service_order_log` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT 'order id',
    `old_status` TINYINT DEFAULT NULL COMMENT 'old order status',
    `new_status` TINYINT DEFAULT NULL COMMENT 'new order status',
    `operator_id` BIGINT UNSIGNED DEFAULT NULL COMMENT 'operator user id',
    `operator_role` TINYINT DEFAULT NULL COMMENT '1 buyer, 2 seller, 3 admin, 4 system',
    `action_type` VARCHAR(50) NOT NULL COMMENT 'action type',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT 'remark',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logical delete flag',
    PRIMARY KEY (`id`),
    KEY `idx_service_order_log_order` (`order_id`, `create_time`),
    KEY `idx_service_order_log_action` (`action_type`),
    CONSTRAINT `fk_service_order_log_order` FOREIGN KEY (`order_id`) REFERENCES `service_order` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='service order log';

CREATE TABLE IF NOT EXISTS `service_dispute` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `order_id` BIGINT UNSIGNED NOT NULL COMMENT 'order id',
    `complainant_id` BIGINT UNSIGNED NOT NULL COMMENT 'complainant user id',
    `respondent_id` BIGINT UNSIGNED NOT NULL COMMENT 'respondent user id',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1 pending, 2 refunded, 3 rejected',
    `reason` VARCHAR(500) NOT NULL COMMENT 'dispute reason',
    `evidence` VARCHAR(1000) DEFAULT NULL COMMENT 'evidence',
    `dispute_type` TINYINT NOT NULL DEFAULT 4 COMMENT 'dispute type: 1 quality, 2 service, 3 timing, 4 other',
    `handle_result` VARCHAR(50) DEFAULT NULL COMMENT 'handle result',
    `handle_remark` VARCHAR(500) DEFAULT NULL COMMENT 'handle remark',
    `handler_id` BIGINT UNSIGNED DEFAULT NULL COMMENT 'handler user id',
    `handle_time` DATETIME DEFAULT NULL COMMENT 'handle time',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
    `is_deleted` TINYINT NOT NULL DEFAULT 0 COMMENT 'logical delete flag',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_service_dispute_order` (`order_id`),
    KEY `idx_service_dispute_complainant` (`complainant_id`, `create_time`),
    KEY `idx_service_dispute_respondent` (`respondent_id`, `create_time`),
    KEY `idx_service_dispute_status` (`status`, `create_time`),
    KEY `idx_service_dispute_handler` (`handler_id`, `handle_time`),
    CONSTRAINT `fk_service_dispute_order` FOREIGN KEY (`order_id`) REFERENCES `service_order` (`id`),
    CONSTRAINT `fk_service_dispute_complainant` FOREIGN KEY (`complainant_id`) REFERENCES `user` (`id`),
    CONSTRAINT `fk_service_dispute_respondent` FOREIGN KEY (`respondent_id`) REFERENCES `user` (`id`),
    CONSTRAINT `fk_service_dispute_handler` FOREIGN KEY (`handler_id`) REFERENCES `user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='service dispute';

CREATE TABLE IF NOT EXISTS `wallet_transaction` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
    `user_id` BIGINT UNSIGNED NOT NULL COMMENT 'user id',
    `transaction_type` TINYINT NOT NULL COMMENT '1 recharge, 2 withdraw, 3 payment, 4 refund, 5 income, 6 freeze, 7 unfreeze',
    `amount` DECIMAL(10, 2) NOT NULL COMMENT 'amount',
    `balance_before` DECIMAL(10, 2) NOT NULL COMMENT 'balance before',
    `balance_after` DECIMAL(10, 2) NOT NULL COMMENT 'balance after',
    `frozen_before` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'frozen before',
    `frozen_after` DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT 'frozen after',
    `related_order_id` BIGINT UNSIGNED DEFAULT NULL COMMENT 'related order id',
    `transaction_no` VARCHAR(64) DEFAULT NULL COMMENT 'transaction number',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT 'remark',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
    PRIMARY KEY (`id`),
    KEY `idx_wallet_transaction_user` (`user_id`, `create_time`),
    KEY `idx_wallet_transaction_order` (`related_order_id`),
    KEY `idx_wallet_transaction_type` (`transaction_type`),
    CONSTRAINT `fk_wallet_transaction_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
    CONSTRAINT `fk_wallet_transaction_order` FOREIGN KEY (`related_order_id`) REFERENCES `service_order` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='wallet transaction';
