server:
  port: 8080

spring:
  application:
    name: xueyifang-gateway
  cloud:
    gateway:
      routes:
        - id: xueyifang-auth
          uri: http://localhost:8100
          predicates:
            - Path=/auth/**
        - id: xueyifang-user
          uri: http://localhost:8200
          predicates:
            - Path=/users/**,/permission/**
        - id: xueyifang-service
          uri: http://localhost:8300
          predicates:
            - Path=/service/**,/service-image/**,/favorite/**,/review/**
        - id: xueyifang-trade
          uri: http://localhost:8400
          predicates:
            - Path=/order/**,/wallet/**,/dispute/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
